### ISSUE TITLE
Where can I find the source code of the sw libraries like  'libivas_xpp.so'  

### ISSUE THREAD

**Issue by luyufan498** [Xilinx/VVAS#2]
I am looking the source code of libivas_xpp.so, libivas_reid.so, libivas_pedpp.so, libivas_drawreid.so, libivas_crop.so ....

Those libraries are used in KV260 examples.

**Comment by nhphuong91** [comment]
@luyufan498 you can find it here: https://github.com/Xilinx/aibox-reid

**Comment by bharatsoni103** [comment]
@luyufan498, is your issue resolved and can we close this issue?

**Comment by bharatsoni103** [comment]
Closing the issue as there is no response. Feel free to re-open in case not resolved.
