### ISSUE TITLE
Failed to build VVAS 3.0 on Ubuntu18.04.2

### ISSUE THREAD

**Issue by yellowd1992** [Xilinx/VVAS#22]
I'm new to VVAS. I tried building VVAS but got the following log which indicates there is no cmake. But I've install cmake and can get its version from 'cmake --version' command. I have installed Vitis AI 3.0 and its sysroots. What should I do?

`yellowd@ubuntu:~/Documents/VVAS$ ./build_install_vvas.sh TARGET=Edge
Default: XRM is disabled
Default: Use of SIMD library disabled
Default: Use of PPE is enabled
Building for Edge
INSTALL_ACCEL_SW = true
TARGET = EDGE
ENABLE_XRM = 0
USE_SIMD = 0
ENABLE_PPE = 1
VVAS_CORE_UTILS = GLIB
Default: Using GLib utils
TARGET = EDGE
USE_SIMD = 0
ENABLE_PPE = 1
VVAS_CORE_UTILS = GLIB
Building for Edge
The Meson build system
Version: 0.58.1
Source dir: /home/yellowd/Documents/VVAS/vvas-core
Build dir: /home/yellowd/Documents/VVAS/vvas-core/build
Build type: cross build
Project name: vvas-libs-core
Project version: 1.0
C compiler for the host machine: /home/yellowd/petalinux_sdk_2022.2/sysroots/x86_64-petalinux-linux/usr/bin/aarch64-xilinx-linux/aarch64-xilinx-linux-gcc (gcc 11.2.0 "aarch64-xilinx-linux-gcc (GCC) 11.2.0")
C linker for the host machine: /home/yellowd/petalinux_sdk_2022.2/sysroots/x86_64-petalinux-linux/usr/bin/aarch64-xilinx-linux/aarch64-xilinx-linux-gcc ld.bfd 2.37.20210721
C++ compiler for the host machine: /home/yellowd/petalinux_sdk_2022.2/sysroots/x86_64-petalinux-linux/usr/bin/aarch64-xilinx-linux/aarch64-xilinx-linux-g++ (gcc 11.2.0 "aarch64-xilinx-linux-g++ (GCC) 11.2.0")
C++ linker for the host machine: /home/yellowd/petalinux_sdk_2022.2/sysroots/x86_64-petalinux-linux/usr/bin/aarch64-xilinx-linux/aarch64-xilinx-linux-g++ ld.bfd 2.37.20210721
Compiler for language c for the build machine not found.
Compiler for language cpp for the build machine not found.
Build machine cpu family: x86_64
Build machine cpu: x86_64
Host machine cpu family: aarch64
Host machine cpu: arm64
Target machine cpu family: aarch64
Target machine cpu: arm64
Message: compiling for Embedded platform
Message: Enabling PPE
Compiler for C++ supports arguments -Wmissing-declarations: YES 
Compiler for C++ supports arguments -Wredundant-decls: YES 
Compiler for C++ supports arguments -Wwrite-strings: YES 
Compiler for C++ supports arguments -Winit-self: YES 
Compiler for C++ supports arguments -Wno-multichar: YES 
Compiler for C++ supports arguments -Wvla: YES 
Compiler for C++ supports arguments -Wpointer-arith: YES 
Compiler for C++ supports arguments -Wmissing-prototypes: NO 
Compiler for C++ supports arguments -Wdeclaration-after-statement: NO 
Compiler for C++ supports arguments -Wold-style-definition: NO 
Compiler for C++ supports arguments -Waggregate-return: YES 
Has header "stdio.h" : YES 
Has header "dlfcn.h" : YES 
Found pkg-config: /home/yellowd/petalinux_sdk_2022.2/sysroots/x86_64-petalinux-linux/usr/bin/pkg-config (0.29.2)
Run-time dependency xrt found: YES 2.14.0
Library uuid found: YES
Library dl found: YES
Library pthread found: YES
Program python3 found: YES (/home/yellowd/petalinux_sdk_2022.2/sysroots/x86_64-petalinux-linux/usr/bin/python3)
Run-time dependency glib-2.0 found: YES 2.68.4
Library vart-util found: YES
Library vitis_ai_library-xnnpp found: YES
Library vitis_ai_library-model_config found: YES
Library vitis_ai_library-dpu_task found: YES
Library opencv_core found: YES
Library vart-runner found: YES
Library libvitis_ai_library-runner_helper found: YES
Library xir found: YES
Library vitis_ai_library-classification found: YES
Library vitis_ai_library-vehicleclassification found: YES
Library vitis_ai_library-yolov2 found: YES
Library vitis_ai_library-yolov3 found: YES
Library vitis_ai_library-refinedet found: YES
Library vitis_ai_library-platedetect found: YES
Library vitis_ai_library-platenum found: YES
Library vitis_ai_library-facedetect found: YES
Library vitis_ai_library-efficientdet_d2 found: YES
Library vitis_ai_library-bcc found: YES
Library vitis_ai_library-ssd found: YES
Library vitis_ai_library-tfssd found: YES
Library vitis_ai_library-ultrafast found: YES
Library vitis_ai_library-lanedetect found: YES
Library vitis_ai_library-facefeature found: YES
Library vitis_ai_library-facelandmark found: YES
Library vitis_ai_library-posedetect found: YES
Library vitis_ai_library-reid found: YES
Library vitis_ai_library-segmentation found: YES
Library vitis_ai_library-graph_runner found: YES
Library protobuf found: YES
Library glog found: YES
Found CMake: NO
Run-time dependency jansson found: NO (tried pkgconfig)
 
dpuinfer/meson.build:251:0: ERROR: Dependency "jansson" not found, tried pkgconfig
 
A full log can be found at /home/yellowd/Documents/VVAS/vvas-core/build/meson-logs/meson-log.txt`

**Comment by MohamedRaizz** [comment]
@yellowd1992 are you find that solution ?
