### ISSUE TITLE
ZCU104 DP platform - wrong Vivado version 

### ISSUE THREAD

**Issue by ksstms** [Xilinx/VVAS#4]
Despite the script being named `xilinx_zcu104_vcuDec_DP_202120_1_xsa.tcl`, the ZCU104 DP platform's Vivado script was generated using 2021.1:
https://github.com/Xilinx/VVAS/blob/3ed13181a59160ccdf78dffed81f38fcc81ba7d5/vvas-platforms/Embedded/zcu104_vcuDec_DP/vivado/xilinx_zcu104_vcuDec_DP_202120_1_xsa.tcl#L70
Of course this gives a warning when building it using Vivado 2021.2.

The PetaLinux version is correct:
https://github.com/Xilinx/VVAS/blob/3ed13181a59160ccdf78dffed81f38fcc81ba7d5/vvas-platforms/Embedded/zcu104_vcuDec_DP/petalinux/.petalinux/metadata#L1

**Comment by rajiv448** [comment]
Hi @ksstms 

This issue has already been addressed in the out latest release. Please check and revert if you still see any issue. 

https://github.com/Xilinx/VVAS/blob/f67c11418c55b5e98595907dafc9848958767bfd/vvas-platforms/Embedded/zcu104_vcuDec_DP/vivado/xilinx_zcu104_vcuDec_DP_xsa.tcl#L75

**Comment by ksstms** [comment]
@rajiv448 This has nothing to do with what I originally posted. The version checking in the original tcl was actually totally fine.

I see that now the Vivado and PetaLinux projects have matching versions (2022.1), so I guess it should be okay. I'm not going to test it though.

**Comment by bharatsoni103** [comment]
Looks like issue is resolved based on last comment. So closing this.
